---
- hosts: localhost
  tasks:
    - name: HTTP Install For Ubuntu
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      package:
        name: apache2
        state: latest
    - name: Start HTTP for Ubuntu
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      service:
        name: apache2
        state: started
        enabled: yes
    - name: HTTP Install For RedHat
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
      package:
        name: httpd
        state: latest
    - name: Start HTTP for RedHat
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
      service:
        name: httpd
        state: started
        enabled: yes