---
- hosts: localhost
  tasks:
    - name: Install PHP and Modules in Ubuntu
      when: ansible_distribution == 'Ubuntu'    
      package:
        name: "{{ items }}"
        state: latest
        with_items: 
          - php-xml
          - php-mcrypt
          - php-mysql
          - php
          - libapache2-mod-php
    - name: Install PHP and Modules in RedHat
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' 
      package:
        name: "{{ items }}"
        state: latest
        with_items: 
          - php-xml
          - php-mcrypt
          - php-mysql
          - php